[tool.black]
line-length = 90
preview = true

[tool.isort]
profile = 'black'
multi_line_output = 3

[tool.ruff]
line-length = 90

select = ["E", "F", "D", "N", "C"]
extend-ignore = [
    "D213", "D203",
]

exclude = [
    "tmp",
    "docs",
]
