[tool.black]
line-length = 90
preview = true

[tool.isort]
profile = 'black'
multi_line_output = 3

[tool.ruff]
line-length = 90

select = ["E", "F", "D", "N", "C"]
extend-ignore = [
    "D102", "D103", "D105", "D107",
    "D205", "D212", "D213", "D203",
    "D401", "D414", "D417",
    "C400", "C408", "C410", "C416", 
    "N802", "N803", "N806", "N818"
]

exclude = [
    "tmp",
    "docs",
]
