[tool.black]
line-length = 90
preview = true

[tool.isort]
profile = 'black'
multi_line_output = 3

[tool.ruff]
line-length = 90

select = ["E", "F", "D", "N", "C"]
extend-ignore = [
    "D213", "D203",
    "D100", "D101", "D102", "D103", "D105", "D107",
    "D200", "D202", "D205", "D207", "D212",
    "D301",
    "D400", "D404", "D405", "D406", "D407", "D409", "D410", "D411", "D412", "D413", "D414", "D415", "D416", "D417",
    "C400", "C408", "C410", "C416", "D401",
    "C901",
    "N802", "N803", "N806", "N818"
]

exclude = [
    "tmp",
    "docs",
]
