[tool.black]
line-length = 90
preview = true

[tool.isort]
profile = 'black'
multi_line_output = 3

[tool.ruff]
line-length = 90

select = ["E", "F", "D", "N", "C"]
extend-ignore = [
    "D213", "D203",
    "D101", "D102", "D107",
    "D200", "D202", "D205", "D212", 
    "D400", "D411", "D414", "D415", "D417",
    "C408", "C416", 
    "N802", "N806", "N818"
]

exclude = [
    "tmp",
    "docs",
]
