name: Check black coding style

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - name: Black Check
      - uses: actions/checkout@v2
      - uses: psf/black@stable